name: tag_animation
description: Tag animation
version: 0.0.2
homepage: https://github.com/lovekid1997/TagAnimation

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
